### ISSUE TITLE
No Emotion Box....

### ISSUE THREAD

**Issue by weebskin** [Jack-Myth/Threshold-Miku#48] opened 2021-04-19 01:50 UTC
![fHV3ZAPBzw](https://user-images.githubusercontent.com/56221357/115171036-5264dd00-a0ec-11eb-8193-44b5c83b85df.gif)
Help?

**Comment by Jack-Myth** [comment] 2021-04-19 02:43
This issue seems doesn't caused by the skin, have you tried the original skin?

**Comment by weebskin** [comment] 2021-04-19 15:33
use original skin is fine but when i use miku skin it happen.

**Comment by Jack-Myth** [comment] 2021-05-30 05:53
takes a very very long time but it fixed now.

**Closed as completed by Jack-Myth** 2021-05-30 05:53 UTC
